name: Compilar IA DLL

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar el codigo
      uses: actions/checkout@v3

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Compilar Solucion de Civ V
      run: msbuild CvGameCoreDLL.vs2008.sln /p:Configuration=Release /p:Platform=Win32

    - name: Capturar la DLL terminada
      uses: actions/upload-artifact@v3
      with:
        name: CvGameCore_Expansion2_Modificada
        # Usamos un comodín para atrapar la DLL sin importar en qué subcarpeta de Release se genere
        path: '**\Release\CvGameCore_Expansion2.dll'